"use client";

import { useEffect, useState } from "react";
import { Download, ExternalLink, Globe2, Pencil, Plus, Printer, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Customer = { id:number; company:string; website:string; industry:string; summary:string; emails:string; phones:string; createdAt:string; updatedAt?:string };
type Lead = { id:string; company:string; website:string; industry:string; summary:string };
export type Product = { id:number; name:string; model:string; category:string; specification:string; price:number; currency:string; status:string };
type Data = { customers:Customer[]; products:Product[] };
const emptyProduct = { id:0, name:"", model:"", category:"", specification:"", price:"", currency:"USD" };

async function fetchData(): Promise<Data> { const r=await fetch("/api/business-data"); const data=await r.json(); if(!r.ok)throw new Error(data.error); return data; }
function csv(filename:string, headers:string[], rows:(string|number)[][]) { const quote=(v:string|number)=>`"${String(v??"").replace(/"/g,'""')}"`; const blob=new Blob(["\ufeff"+[headers,...rows].map(row=>row.map(quote).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}); const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href); }

export function CustomerResearchView(){
  const [customers,setCustomers]=useState<Customer[]>([]),[leads,setLeads]=useState<Lead[]>([]),[keyword,setKeyword]=useState(""),[region,setRegion]=useState(""),[website,setWebsite]=useState(""),[company,setCompany]=useState(""),[loading,setLoading]=useState(false),[query,setQuery]=useState(""),[refreshing,setRefreshing]=useState(false);
  useEffect(()=>{fetchData().then(d=>{setCustomers(d.customers);const stale=d.customers.some(x=>Date.now()-new Date(x.updatedAt||x.createdAt).getTime()>86400000);if(stale)void refreshAll(false)}).catch(()=>{})},[]);
  async function discover(){if(!keyword.trim())return toast.error("请输入产品或行业关键词");setLoading(true);try{const r=await fetch("/api/business-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"discoverLeads",keyword,region})});const data=await r.json();if(!r.ok)throw new Error(data.error);setLeads(data.leads||[]);if(!data.leads?.length)toast.info("没有找到结果，请换一个英文关键词")}catch(e){toast.error(e instanceof Error?e.message:"客户搜索失败")}finally{setLoading(false)}}
  async function archive(lead:Lead){try{const r=await fetch("/api/business-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"researchCustomer",website:lead.website,company:lead.company})});const data=await r.json();if(!r.ok)throw new Error(data.error);setCustomers(current=>[data.customer,...current]);toast.success("客户官网、行业与联系方式已存档")}catch(e){toast.error(e instanceof Error?e.message:"官网分析失败")}}
  async function archiveWebsite(){if(!website.trim())return toast.error("请输入客户官网");await archive({id:"manual",company:company.trim(),website,industry:"待分析",summary:""});setWebsite("");setCompany("")}
  async function refreshAll(notify=true){setRefreshing(true);try{const r=await fetch("/api/business-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"refreshCustomers"})});const data=await r.json();if(!r.ok)throw new Error(data.error);const latest=await fetchData();setCustomers(latest.customers);if(notify)toast.success(`已更新 ${data.updated}/${data.total} 个客户`)}catch(e){if(notify)toast.error(e instanceof Error?e.message:"更新失败")}finally{setRefreshing(false)}}
  const rows=customers.filter(x=>`${x.company}${x.website}${x.industry}${x.emails}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="intel-page"><section className="research-hero"><div><span>LEAD DISCOVERY & INTELLIGENCE</span><h2>潜在客户搜索与行业情报</h2><p>按产品、行业和市场寻找新客户，确认后再分析官网并存入客户档案。</p></div><Globe2/></section><section className="research-box lead-search"><label>产品 / 行业关键词<Input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="例如 mobile phone distributor"/></label><label>国家或地区<Input value={region} onChange={e=>setRegion(e.target.value)} placeholder="例如 UAE / Germany" onKeyDown={e=>e.key==='Enter'&&void discover()}/></label><div className="lead-search-actions"><Button disabled={loading} onClick={()=>void discover()}><Search/>{loading?"正在搜索潜在客户…":"搜索新客户"}</Button><a target="_blank" rel="noreferrer" href={`https://www.google.com/search?q=${encodeURIComponent(`${keyword} ${region} distributor importer company`)}`}>浏览器深度搜索</a></div></section><section className="direct-archive"><div><b>已经找到客户官网吗？</b><span>自动分析行业、公开邮箱和电话，并永久保留客户档案。</span></div><Input value={company} onChange={e=>setCompany(e.target.value)} placeholder="客户公司（可选）"/><Input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="www.customer.com"/><Button variant="outline" onClick={()=>void archiveWebsite()}>分析官网并存档</Button></section>{leads.length>0&&<section className="lead-results"><div className="archive-title"><div><Search/><h3>潜在客户结果</h3></div><small>共 {leads.length} 条，存档前不会进入客户库</small></div>{leads.map(lead=><article key={lead.id}><div><small>{lead.industry}</small><h3>{lead.company}</h3><p>{lead.summary}</p><a href={lead.website} target="_blank" rel="noreferrer">{lead.website}<ExternalLink/></a></div><Button onClick={()=>void archive(lead)}>分析官网并存档</Button></article>)}</section>}<div className="section-tools customer-archive-head"><div><span className="eyebrow">SAVED CUSTOMER ARCHIVE</span><h2>已保存客户档案</h2><div className="search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="在已保存客户中筛选"/></div></div><div><Button variant="outline" disabled={refreshing} onClick={()=>void refreshAll()}>{refreshing?"正在更新…":"立即更新行业信息"}</Button><Button variant="outline" onClick={()=>csv("TradeFlow客户情报.csv",["公司","官网","行业","简介","邮箱","电话","更新时间"],rows.map(x=>[x.company,x.website,x.industry,x.summary,x.emails,x.phones,x.updatedAt||x.createdAt]))}><Download/>导出 CSV</Button><Button variant="outline" onClick={()=>window.print()}><Printer/>客户版 PDF</Button></div></div><section className="intel-grid">{rows.map(x=><article className="intel-card" key={x.id}><header><div><small>{x.industry}</small><h3>{x.company}</h3></div><a href={x.website} target="_blank" rel="noreferrer"><ExternalLink/></a></header><p>{x.summary||"官网未提供简介"}</p><dl><div><dt>公开邮箱</dt><dd>{x.emails||"未识别"}</dd></div><div><dt>公开电话</dt><dd>{x.phones||"未识别"}</dd></div></dl><footer>每日更新 · 最近 {new Date(x.updatedAt||x.createdAt).toLocaleString("zh-CN")}</footer></article>)}</section>{!rows.length&&<div className="empty-intel">客户档案为空。先在上方搜索潜在客户，再选择“分析官网并存档”。</div>}</div>
}

export function ProductManager(){
  const [products,setProducts]=useState<Product[]>([]),[open,setOpen]=useState(false),[draft,setDraft]=useState(emptyProduct),[query,setQuery]=useState("");
  useEffect(()=>{fetchData().then(d=>setProducts(d.products)).catch(()=>{})},[]);
  function edit(p?:Product){setDraft(p?{...p,price:String(p.price/100)}:emptyProduct);setOpen(true)}
  async function save(){if(!draft.name.trim()||!draft.model.trim())return toast.error("请填写产品名称和型号");try{const r=await fetch("/api/business-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"saveProduct",...draft})});const data=await r.json();if(!r.ok)throw new Error(data.error);setProducts(current=>[data.product,...current.filter(x=>x.id!==data.product.id)]);setOpen(false);toast.success("产品资料已存档")}catch(e){toast.error(e instanceof Error?e.message:"保存失败")}}
  async function remove(id:number){await fetch("/api/business-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"deleteProduct",id})});setProducts(products.filter(x=>x.id!==id));toast.success("产品已删除")}
  const rows=products.filter(x=>`${x.name}${x.model}${x.category}${x.specification}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="product-page"><div className="section-tools"><div><span className="eyebrow">PRODUCT MASTER DATA</span><h2>产品信息库</h2><p>规格、价格和型号统一存档，制作 PI / CI / PL 时自动调用。</p></div><div className="no-print"><Button variant="outline" onClick={()=>csv("TradeFlow产品资料.csv",["产品名称","型号","分类","规格","价格","币种"],rows.map(x=>[x.name,x.model,x.category,x.specification,(x.price/100).toFixed(2),x.currency]))}><Download/>导出 CSV</Button><Button variant="outline" onClick={()=>window.print()}><Printer/>客户版 PDF</Button><Button onClick={()=>edit()}><Plus/>新增产品</Button></div></div><div className="product-search no-print"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索产品、型号、分类或规格"/></div><section className="product-grid">{rows.map(p=><article className="product-card" key={p.id}><div className="product-cover"><span>{p.model.slice(0,2).toUpperCase()}</span></div><div><small>{p.category||"未分类"}</small><h3>{p.name}</h3><b>{p.model}</b><p>{p.specification||"暂未录入规格"}</p><strong>{p.currency} {(p.price/100).toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><footer className="no-print"><Button size="sm" variant="outline" onClick={()=>edit(p)}><Pencil/>编辑</Button><Button size="sm" variant="ghost" onClick={()=>void remove(p.id)}><Trash2/>删除</Button></footer></article>)}</section>{!rows.length&&<div className="empty-intel">尚无产品资料。点击“新增产品”开始建立产品库。</div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{draft.id?"编辑产品":"新增产品"}</DialogTitle><DialogDescription>保存后可以在业务单据中按型号自动关联。</DialogDescription></DialogHeader>{[["name","产品名称"],["model","型号"],["category","分类"],["specification","规格参数"],["price","参考单价"]].map(([key,label])=><label className="product-field" key={key}>{label}<Input value={String(draft[key as keyof typeof draft])} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label className="product-field">币种<select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}><option>USD</option><option>EUR</option><option>CNY</option></select></label><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>取消</Button><Button onClick={()=>void save()}>保存产品</Button></DialogFooter></DialogContent></Dialog></div>
}
