"use client";
import {useEffect,useMemo,useState} from "react";
import {BookOpen,CheckCircle2,Circle,Clock3,GraduationCap,Search} from "lucide-react";
import {Input} from "@/components/ui/input";import {Button} from "@/components/ui/button";import {toast} from "sonner";
type Lesson={id:string;category:string;title:string;minutes:number;level:string;summary:string;points:string[]};
const lessons:Lesson[]=[
{id:"customer",category:"客户开发",title:"外贸客户开发与客户画像",minutes:35,level:"入门",summary:"从目标市场、渠道类型和采购特征建立客户画像。",points:["定义 ICP 目标客户","判断进口商、分销商与零售商","整理官网、邮箱和采购线索"]},
{id:"email",category:"客户开发",title:"开发信与跟进节奏",minutes:30,level:"入门",summary:"编写简短开发信，并建立多轮跟进计划。",points:["主题行与首段写法","产品价值表达","第 1、3、7、14 天跟进"]},
{id:"inquiry",category:"询盘转化",title:"询盘分析与报价前确认",minutes:40,level:"进阶",summary:"识别真实需求、成交概率和报价风险。",points:["核实公司与采购身份","确认数量、规格和认证","区分价格询问与真实项目"]},
{id:"quote",category:"单据实务",title:"报价单、PI、CI 与 PL",minutes:55,level:"实务",summary:"理解各类外贸单据的用途、字段和衔接关系。",points:["报价与 PI 的区别","CI 金额与贸易条款","PL 箱号、毛净重和体积"]},
{id:"incoterms",category:"贸易条款",title:"EXW、FOB、CIF、DDP 风险划分",minutes:45,level:"进阶",summary:"按费用、风险和清关责任选择贸易术语。",points:["交货地点与风险转移","海运费和保险责任","DDP 税务及清关风险"]},
{id:"payment",category:"风险控制",title:"T/T、L/C 与收款风险",minutes:45,level:"进阶",summary:"设计付款节点并识别高风险付款条件。",points:["定金比例与尾款节点","信用证常见不符点","水单不等于实际到账"]},
{id:"shipping",category:"订单交付",title:"生产、验货与国际物流",minutes:50,level:"实务",summary:"从订单确认到装柜出货建立关键节点。",points:["交期倒排与异常提醒","验货与包装资料","订舱、提单和出货文件"]},
{id:"compliance",category:"合规认证",title:"产品认证与出口合规",minutes:40,level:"进阶",summary:"按国家和产品管理认证、标签与资料有效期。",points:["CE、FCC 等常见认证","电池和运输资料","客户及制裁风险核验"]}];
const key="tradeflow.github.learning";
export default function LearningCenter(){const[done,setDone]=useState<string[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[active,setActive]=useState(lessons[0]),[query,setQuery]=useState(""),[category,setCategory]=useState("全部");useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(key)||"{}");setDone(v.done||[]);setNotes(v.notes||{})}catch{}},[]);function save(nextDone=done,nextNotes=notes){setDone(nextDone);setNotes(nextNotes);localStorage.setItem(key,JSON.stringify({done:nextDone,notes:nextNotes,updatedAt:new Date().toISOString()}))}const categories=["全部",...new Set(lessons.map(x=>x.category))],shown=lessons.filter(x=>(category==="全部"||x.category===category)&&`${x.title}${x.summary}${x.category}`.toLowerCase().includes(query.toLowerCase())),progress=Math.round(done.length/lessons.length*100),minutes=useMemo(()=>lessons.filter(x=>done.includes(x.id)).reduce((s,x)=>s+x.minutes,0),[done]);return <div className="learning-page stack"><div className="head"><div className="page"><span>TRADE KNOWLEDGE</span><h2>外贸课程学习</h2></div><div className="learning-progress"><b>{progress}%</b><span>已完成 {done.length}/{lessons.length} 课 · {minutes} 分钟</span><i><em style={{width:`${progress}%`}}/></i></div></div><section className="lead"><div><span>体系化学习</span><h2>从客户开发到订单交付</h2><p>课程进度和个人笔记保存在当前浏览器，可随业务实践持续补充。</p></div><GraduationCap/></section><div className="learning-tools"><div className="search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索课程内容"/></div><div className="filters">{categories.map(x=><Button size="sm" key={x} variant={category===x?"default":"outline"} onClick={()=>setCategory(x)}>{x}</Button>)}</div></div><div className="learning-layout"><section className="course-list">{shown.map(course=><button className={`course-card ${active.id===course.id?"active":""}`} key={course.id} onClick={()=>setActive(course)}><span onClick={e=>{e.stopPropagation();const next=done.includes(course.id)?done.filter(x=>x!==course.id):[...done,course.id];save(next);toast.success(next.includes(course.id)?"课程已完成":"已取消完成状态")}}>{done.includes(course.id)?<CheckCircle2/>:<Circle/>}</span><div><small>{course.category} · {course.level}</small><h3>{course.title}</h3><p>{course.summary}</p><time><Clock3/>{course.minutes} 分钟</time></div></button>)}</section><section className="panel lesson-detail"><small>{active.category} · {active.level}</small><h2>{active.title}</h2><p>{active.summary}</p><h3>本课要点</h3><ol>{active.points.map(x=><li key={x}>{x}</li>)}</ol><label>学习笔记<textarea value={notes[active.id]||""} onChange={e=>save(done,{...notes,[active.id]:e.target.value})} placeholder="记录客户案例、问题和行动计划…"/></label><Button onClick={()=>{const next=done.includes(active.id)?done.filter(x=>x!==active.id):[...done,active.id];save(next)}}>{done.includes(active.id)?<><CheckCircle2/>已完成，点击取消</>:<><BookOpen/>标记完成</>}</Button></section></div></div>}
