"use client";
import {useEffect,useState} from "react";import {toast} from "sonner";import {Archive,BarChart3,Bell,BookOpen,Bookmark,BookmarkCheck,Boxes,BriefcaseBusiness,CalendarDays,ChevronRight,CircleDollarSign,Clock3,ExternalLink,FileSpreadsheet,LayoutDashboard,Menu,Newspaper,PackageCheck,Plus,Search,ShieldCheck,Sparkles,Upload,Users} from "lucide-react";
import {Sidebar,SidebarContent,SidebarGroup,SidebarGroupContent,SidebarGroupLabel,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger} from "@/components/ui/sidebar";import {Button} from "@/components/ui/button";import {Input} from "@/components/ui/input";import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";import {Toaster} from "@/components/ui/sonner";
import DocumentsWorkspace from "./documents-workspace";
import {CustomerResearchView,ProductManager} from "./business-data-center";
import LearningCenter from "./learning-center";
import CloudSync from "./cloud-sync";
type View="workbench"|"customers"|"pipeline"|"orders"|"materials"|"documents"|"industry"|"learning"|"sync"|"reports"|"team"|"guide";type Deal={id:string;customer:string;product:string;amount:number;stage:string;next:string;owner:string};
const nav=[['workbench','工作台',LayoutDashboard],['customers','客户与线索',Users],['pipeline','商机漏斗',BriefcaseBusiness],['orders','订单与交付',PackageCheck],['materials','产品素材',Boxes],['documents','业务单据',FileSpreadsheet],['industry','行业情报',Newspaper],['learning','外贸课程',BookOpen],['sync','数据云同步',Archive],['reports','经营报表',BarChart3],['team','团队与权限',ShieldCheck],['guide','使用指南',BookOpen]] as const;
const stages=[['inquiry','询盘','#4b6b92'],['contacted','已联系','#327b84'],['quoted','已报价','#9a6b2f'],['sample','寄样','#795aa6'],['negotiation','谈判','#ba633e'],['won','成交','#2d7a58']] as const;
const initial:Deal[]=[{id:'OP-260901',customer:'Copier International',product:'E7 Elite 5G',amount:156060,stage:'quoted',next:'确认付款水单',owner:'Wendy'},{id:'OP-260902',customer:'Nordic Mobile AB',product:'E5 Elite',amount:82400,stage:'sample',next:'9月16日确认样机反馈',owner:'Wendy'},{id:'OP-260903',customer:'Kanto Retail',product:'NE81',amount:217800,stage:'negotiation',next:'更新包装与交期',owner:'Kevin'},{id:'OP-260904',customer:'Andes Telecom',product:'E7 Life',amount:75600,stage:'contacted',next:'发送认证资料',owner:'Lina'},{id:'OP-260905',customer:'Ralph Ltd',product:'MTK6500',amount:98000,stage:'won',next:'安排出货',owner:'Wendy'}];
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);const customers=[['Copier International','阿联酋','A','已报价','今天 09:20','确认付款水单','Wendy','正常'],['Nordic Mobile AB','瑞典','A','寄样','昨天 16:45','样机反馈','Wendy','3天未跟'],['Kanto Retail','日本','S','谈判','9月12日','包装与交期','Kevin','高价值'],['Andes Telecom','智利','B','已联系','9月10日','发送认证','Lina','4天未跟']];
export default function TradeFlowApp(){const[view,setView]=useState<View>('workbench'),[deals,setDeals]=useState(initial),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[draft,setDraft]=useState({customer:'',product:'',amount:''});const title=nav.find(n=>n[0]===view)?.[1];useEffect(()=>{fetch('/api/deals').then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(data.deals?.length)setDeals([...data.deals,...initial])}).catch(()=>{})},[]);async function createDeal(input:{customer:string;product:string;amount:number}){const response=await fetch('/api/deals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});const data=await response.json();if(!response.ok)throw new Error(data.error||'保存失败');setDeals(current=>[data.deal,...current]);return data.deal as Deal}async function add(){if(!draft.customer||!draft.product||Number(draft.amount)<=0)return toast.error('请填写客户、产品和有效金额');try{await createDeal({customer:draft.customer,product:draft.product,amount:Number(draft.amount)});setOpen(false);setDraft({customer:'',product:'',amount:''});toast.success('商机已保存并加入询盘阶段')}catch(error){toast.error(error instanceof Error?error.message:'保存失败')}}useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'create_sales_opportunity',title:'新增销售商机',description:'在 TradeFlow 中创建一条销售商机并保存到询盘阶段。',inputSchema:{type:'object',properties:{customer:{type:'string'},product:{type:'string'},amount:{type:'number',exclusiveMinimum:0}},required:['customer','product','amount'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const value=input as {customer?:string;product?:string;amount?:number};if(!value.customer?.trim()||!value.product?.trim()||!value.amount||value.amount<=0)throw new Error('客户、产品和金额必须有效');const deal=await createDeal({customer:value.customer,product:value.product,amount:value.amount});return{id:deal.id,stage:deal.stage}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[])
return <SidebarProvider><Sidebar className="trade-sidebar"><SidebarHeader><div className="brand"><span><Sparkles/></span><div><b>TradeFlow</b><small>外贸业务平台</small></div></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>业务中心</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton className="trade-nav" isActive={view===id} onClick={()=>setView(id)}><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><div className="sync-card"><b><i/>当前浏览器本地存储</b><p>换设备前请先导出客户与业务资料</p></div></Sidebar><SidebarInset className="app-bg"><header className="topbar"><div><SidebarTrigger className="md:hidden"><Menu/></SidebarTrigger><span>TRADE OPERATIONS</span><h1>{title}</h1></div><div><Button variant="outline" size="icon"><Bell/></Button><Button className="gold" onClick={()=>setOpen(true)}><Plus/>新增商机</Button></div></header><main>{view==='workbench'&&<Workbench deals={deals} go={setView}/>} {view==='customers'&&<Customers query={query} setQuery={setQuery}/>} {view==='pipeline'&&<Pipeline deals={deals} setDeals={setDeals}/>} {view==='orders'&&<Orders/>} {view==='materials'&&<Materials/>} {view==='documents'&&<Documents/>} {view==='industry'&&<IndustryIntel/>} {view==='learning'&&<LearningCenter/>} {view==='sync'&&<CloudSync/>} {view==='reports'&&<Reports deals={deals}/>} {view==='team'&&<Team/>} {view==='guide'&&<Guide/>}</main></SidebarInset><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>新增销售商机</DialogTitle><DialogDescription>保存后进入询盘阶段，可在漏斗中继续推进。</DialogDescription></DialogHeader><Field label="客户公司"><Input value={draft.customer} onChange={e=>setDraft({...draft,customer:e.target.value})}/></Field><Field label="产品 / 机型"><Input value={draft.product} onChange={e=>setDraft({...draft,product:e.target.value})}/></Field><Field label="预计金额 USD"><Input value={draft.amount} inputMode="decimal" onChange={e=>setDraft({...draft,amount:e.target.value})}/></Field><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>取消</Button><Button onClick={add}>保存商机</Button></DialogFooter></DialogContent></Dialog><Toaster richColors/></SidebarProvider>}
function Workbench({deals,go}:{deals:Deal[];go:(v:View)=>void}){const active=deals.filter(d=>d.stage!=='won'),won=deals.filter(d=>d.stage==='won').reduce((s,d)=>s+d.amount,0);return <div className="stack"><section className="lead"><div><span>9月14日 · 周一</span><h2>今天先处理 3 项高价值动作</h2><p>报价确认、样机反馈和交付风险已按影响金额排序。</p></div><Button variant="secondary" onClick={()=>go('pipeline')}>查看商机漏斗<ChevronRight/></Button></section><div className="metrics"><Metric icon={BriefcaseBusiness} label="进行中商机" value={String(active.length)} note={money(active.reduce((s,d)=>s+d.amount,0))}/><Metric icon={CircleDollarSign} label="本月成交" value={money(won)} note="目标完成 68%"/><Metric icon={PackageCheck} label="待处理订单" value="3" note="1 笔交期未确认"/><Metric icon={Clock3} label="逾期跟进" value="2" note="最久 4 天"/></div><div className="main-grid"><section className="panel"><Heading over="行动队列" title="今日优先事项"/><Task time="09:30" title="确认 MEAHTC2026081402 付款水单" sub="Copier International · USD 156,060"/><Task time="11:00" title="回访 E5 Elite 样机测试" sub="Nordic Mobile AB · 已寄出 3 天"/><Task time="15:00" title="提交 Kanto 包装与交期方案" sub="预计金额 USD 217,800"/></section><section className="panel"><Heading over="销售健康度" title="本周漏斗"/><div className="mini">{stages.map(([id,label,color])=><div key={id}><span>{label}</span><i style={{width:`${Math.max(12,deals.filter(d=>d.stage===id).length*32)}%`,background:color}}/><b>{deals.filter(d=>d.stage===id).length}</b></div>)}</div></section></div><section className="panel"><Heading over="风险雷达" title="需要留意"/><div className="risks"><Risk title="交付日期缺失" value="MEAHTC2026081402" sub="订单已录入，目标交期尚未确认"/><Risk title="认证即将到期" value="E7 Elite · CE" sub="剩余 26 天，请提前安排更新"/><Risk title="报价后未回复" value="Andes Telecom" sub="USD 75,600 · 已等待 4 天"/></div></section></div>}
function Customers({query,setQuery}:{query:string;setQuery:(x:string)=>void}){void query;void setQuery;return <CustomerResearchView/>}
function Pipeline({deals,setDeals}:{deals:Deal[];setDeals:React.Dispatch<React.SetStateAction<Deal[]>>}){async function move(id:string,stage:string){const before=deals;setDeals(current=>current.map(d=>d.id===id?{...d,stage}:d));if(initial.some(d=>d.id===id))return toast.success('演示商机阶段已更新');try{const response=await fetch('/api/deals',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,stage})});if(!response.ok)throw new Error();toast.success('商机阶段已保存')}catch{setDeals(before);toast.error('阶段保存失败，请重试')}}return <div><Page over="可视化销售过程" title="商机漏斗"/><div className="pipeline">{stages.map(([id,label,color])=><section className="column" key={id}><header style={{borderTopColor:color}}><b>{label}</b><span>{deals.filter(d=>d.stage===id).length}</span></header>{deals.filter(d=>d.stage===id).map(d=><article className="deal" key={d.id}><small>{d.id} · {d.owner}</small><h3>{d.customer}</h3><p>{d.product}</p><b>{money(d.amount)}</b><div><Clock3/>{d.next}</div><select aria-label="商机阶段" value={d.stage} onChange={e=>void move(d.id,e.target.value)}>{stages.map(([x,l])=><option key={x} value={x}>{l}</option>)}</select></article>)}</section>)}</div></div>}
function Orders(){const rows=[['MEAHTC2026081402','Copier International','E7 Elite / E5 Elite','1,428','$156,060','待确认','100% TT · 未核实到账','待确认'],['SO-260812','Ralph Ltd','MTK6500','250','$100,000','9月22日','已收定金','生产中'],['SO-260815','Kanto Retail','NE81','900','$217,800','10月08日','30% / 70%','待排产']];return <div className="stack"><div className="head"><Page over="从 PDF 到交付" title="订单与交付"/><Button onClick={()=>toast.info('将复用你现有系统的 PDF 解析规则')}><Upload/>识别 PDF 订单</Button></div><div className="metrics"><Metric icon={CircleDollarSign} label="本月订单额" value="$473,860" note="3 笔订单"/><Metric icon={CalendarDays} label="待确认交期" value="1" note="影响 1,428 台"/><Metric icon={PackageCheck} label="生产中" value="250" note="预计 9月22日交付"/><Metric icon={ShieldCheck} label="待核实收款" value="$156,060" note="条款不等于到账"/></div><section className="panel"><Data headers={['订单编号','客户','产品','数量','金额','交付日期','付款','状态']} rows={rows}/></section></div>}
function Materials(){return <ProductManager/>}
function Collection({name}:{name:string}){const gs=['全部素材','合集共用','产品实拍','包装图','认证资料'],[active,setActive]=useState(gs[0]);return <section className="panel"><div className="head"><div><h3>{name}</h3><p className="muted">6+128 GB · 5G · 5600mAh · Android 15</p></div><Button variant="outline" onClick={()=>toast.info('支持批量上传图片、视频与资料')}>批量添加素材</Button></div><div className="filters">{gs.map(g=><Button size="sm" key={g} variant={g===active?'default':'outline'} onClick={()=>setActive(g)}>{g}</Button>)}</div><div className="assets">{['正面主图','Champagne Gold','包装清单','CE 认证','工厂实拍','彩盒设计'].map((x,i)=><article key={x}><div className={`asset a${i}`}><Boxes/></div><b>{x}</b><small>{i<2?'合集共用':i===3?'认证资料':'产品分组'}</small></article>)}</div></section>}
function Documents(){return <DocumentsWorkspace/>}
type IndustryItem={title:string;link:string;source:string;published:string;category:string;summary:string;summaryZh?:string};type IndustrySummary={category:string;count:number;overview:string;focus:string};
function industrySummaryZh(item:IndustryItem){if(item.summaryZh)return item.summaryZh;const guidance:{[key:string]:string}={"手机与消费电子":"主要涉及新品、关键零部件、产品规格或品牌动向，建议关注价格、上市节奏及产品规划。","市场与渠道":"主要涉及市场需求、渠道布局、企业合作或销售变化，建议关注客户机会与竞争格局。","物流与供应链":"主要涉及物流服务、供应链合作、运输效率或中断风险，建议关注运价、交期及供应稳定性。","法规与合规":"主要涉及产品准入、认证、关税或监管变化，建议核对目标市场的合规要求与生效时间。"};return `本条资讯关注“${item.title.replace(/\s+-\s+[^-]+$/,"")}”。${guidance[item.category]||"建议结合客户、价格、交期和合规要求评估对业务的影响。"}`}
function IndustryIntel(){
  const storageKey="tradeflow.github.industry.saved";
  const[items,setItems]=useState<IndustryItem[]>([]),[summaries,setSummaries]=useState<IndustrySummary[]>([]),[saved,setSaved]=useState<IndustryItem[]>([]),[updated,setUpdated]=useState(""),[filter,setFilter]=useState("全部"),[loading,setLoading]=useState(true);
  useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem(storageKey)||"[]"))}catch{}},[]);
  const load=()=>{setLoading(true);fetch(new URL("data/industry-news.json",document.baseURI),{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{setItems(data.items??[]);setSummaries(data.summaries??[]);setUpdated(data.updatedAt??"")}).catch(()=>setItems([])).finally(()=>setLoading(false))};
  const collect=()=>{window.open("https://github.com/wendyphang621-maker/tradeflow-platform/actions/workflows/update-industry-news.yml","_blank","noopener,noreferrer");toast.info("在 GitHub 页面点击 Run workflow 即可立即收集，不依赖 GPT")};
  useEffect(load,[]);
  function toggleSave(item:IndustryItem){const exists=saved.some(x=>x.link===item.link),next=(exists?saved.filter(x=>x.link!==item.link):[{...item,savedAt:new Date().toISOString()} as IndustryItem,...saved]).slice(0,500);setSaved(next);localStorage.setItem(storageKey,JSON.stringify(next));toast.success(exists?"已取消收藏":"已保存到稍后阅读")}
  const categories=["全部","已收藏",...Array.from(new Set(items.map(x=>x.category)))],base=filter==="已收藏"?saved:items,shown=filter==="全部"?items:filter==="已收藏"?saved:base.filter(x=>x.category===filter);
  return <div className="stack"><div className="head"><Page over="每日公开信息汇总" title="行业情报"/><div><Button onClick={collect}><Newspaper/>启动收集</Button><Button variant="outline" onClick={load}>刷新结果</Button></div></div><section className="lead"><div><span>自动更新 · 无需 GPT</span><h2>独立收集并整理手机行业动态</h2><p>公开 RSS → GitHub 自动任务 → 中英文概要 → 稍后阅读收藏。收藏后即使每日更新也会保留。</p></div><div><b>{items.length} 条 · 收藏 {saved.length} 条</b><p className="muted">{updated?`更新于 ${new Date(updated).toLocaleString("zh-CN")}`:"等待首次更新"}</p></div></section><div className="industry-summary-grid">{summaries.map(x=><article className="panel" key={x.category}><span className="eyebrow">{x.category} · {x.count} 条</span><h3>{x.overview}</h3><p className="muted">关注建议：{x.focus}</p></article>)}</div><div className="filters">{categories.map(x=><Button size="sm" key={x} variant={x===filter?"default":"outline"} onClick={()=>setFilter(x)}>{x==="已收藏"?`已收藏 (${saved.length})`:x}</Button>)}</div><section className="panel">{loading?<p className="muted">正在读取行业信息…</p>:shown.length?shown.map((item,i)=>{const isSaved=saved.some(x=>x.link===item.link);return <article className="task industry-item" key={`${item.link}-${i}`}><time>{item.category}</time><div><a href={item.link} target="_blank" rel="noreferrer"><b>{item.title}</b></a><p className="industry-cn"><b>中文概要：</b>{industrySummaryZh(item)}</p><p className="industry-en"><b>English summary: </b>{item.summary||`${item.source} · ${item.published}`}</p><small>{item.source} · {item.published?new Date(item.published).toLocaleDateString("zh-CN"):""}</small></div><div className="industry-actions"><Button size="sm" variant={isSaved?"default":"outline"} onClick={()=>toggleSave(item)}>{isSaved?<BookmarkCheck/>:<Bookmark/>}{isSaved?"已收藏":"稍后阅读"}</Button><a href={item.link} target="_blank" rel="noreferrer" aria-label="打开原文"><ExternalLink/></a></div></article>}):<p className="muted">{filter==="已收藏"?"还没有收藏资讯。点击资讯右侧的“稍后阅读”即可保存。":"行业信息正在生成。点击“启动收集”，在 GitHub 页面运行任务即可更新。"}</p>}</section></div>}
function Guide(){const steps=[["1. 工作台","查看重点事项、成交额、待处理订单和风险提示。"],["2. 客户与线索","输入行业关键词检索公开客户；确认官网后存档客户资料。"],["3. 商机漏斗","新增商机，并在询盘、联系、报价、寄样、谈判和成交之间推进。"],["4. 订单与交付","查看订单金额、数量、付款和交期；PDF 订单识别请在本地完整版使用。"],["5. 产品素材","新增产品资料并维护型号、规格、报价和素材分组。"],["6. 业务单据","维护公司抬头，制作并存档 PI、CI、PL；使用打印功能输出 PDF。"],["7. 行业情报","阅读每日自动更新的产品、市场、渠道、物流与合规资讯。"],["8. 数据安全","GitHub 版本把业务数据保存在当前浏览器。换电脑或清理浏览器前请先导出资料。"]];return <div className="stack"><div className="head"><Page over="从录入到交付" title="使用指南"/><Button asChild variant="outline"><a href="TradeFlow使用指南.md" download><BookOpen/>下载指南</a></Button></div><section className="lead"><div><span>快速开始</span><h2>建议按“产品 → 客户 → 商机 → 单据”顺序使用</h2><p>先建立产品与公司抬头，再录入客户和商机，成交后制作 PI、CI、PL。</p></div></section><section className="panel roles">{steps.map(([title,detail])=><article key={title}><BookOpen/><div><b>{title}</b><p>{detail}</p></div></article>)}</section><section className="panel"><Heading over="GitHub 版本说明" title="数据保存在哪里"/><p className="muted">本版本不需要服务器账号，数据保存在当前浏览器的本地存储中。同一网址在不同电脑或不同浏览器中不会自动同步。公开网页不会公开你录入的客户数据。</p></section></div>}
function Reports({deals}:{deals:Deal[]}){const total=deals.reduce((s,d)=>s+d.amount,0);return <div><Page over="真实业务数据汇总" title="经营报表"/><div className="report-grid"><section className="panel"><h3>商机金额分布</h3><div className="bars">{stages.map(([id,label,color])=>{const n=deals.filter(d=>d.stage===id).reduce((s,d)=>s+d.amount,0);return <div key={id}><span>{label}</span><i><em style={{width:`${Math.max(3,n/total*100)}%`,background:color}}/></i><b>{money(n)}</b></div>})}</div></section><section className="panel"><h3>重点市场</h3>{[['中东','$254,060'],['东亚','$217,800'],['欧洲','$180,400'],['南美','$75,600']].map(x=><div className="market" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</section></div></div>}
function Team(){return <div><Page over="清晰的数据边界" title="团队与权限"/><section className="panel roles">{[['管理员','系统配置、全部业务、权限审计'],['销售主管','团队客户、商机、报表与审批'],['业务员','本人客户、商机、任务与单据'],['只读财务','订单、收款与导出记录']].map(([a,b])=><article key={a}><ShieldCheck/><div><b>{a}</b><p>{b}</p></div></article>)}</section></div>}
function Field(p:{label:string;children:React.ReactNode}){return <label className="field">{p.label}{p.children}</label>}function Page(p:{over:string;title:string}){return <div className="page"><span>{p.over}</span><h2>{p.title}</h2></div>}function Heading(p:{over:string;title:string}){return <div className="heading"><span>{p.over}</span><h3>{p.title}</h3></div>}function Metric({icon:Icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <article className="metric"><div><span>{label}</span><b>{value}</b><small>{note}</small></div><i><Icon/></i></article>}function Task(p:{time:string;title:string;sub:string}){return <article className="task"><time>{p.time}</time><div><b>{p.title}</b><p>{p.sub}</p></div><ChevronRight/></article>}function Risk(p:{title:string;value:string;sub:string}){return <article className="risk"><span>{p.title}</span><b>{p.value}</b><p>{p.sub}</p></article>}function Data({headers,rows}:{headers:string[];rows:string[][]}){return <Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{r.map((v,j)=><TableCell className={j===0?'font-semibold':''} key={j}>{j===r.length-1?<span className={`status ${v==='正常'||v==='已批准'?'ok':''}`}>{v}</span>:v}</TableCell>)}</TableRow>)}</TableBody></Table>}






