import { and, desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { customerResearch, products } from "../../../db/schema";

const owner = (request: Request) => request.headers.get("oai-authenticated-user-id") ?? "local_seedy";
const textOnly = (html: string) => html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&nbsp;|&#160;/gi, " ").replace(/&amp;/gi, "&").replace(/\s+/g, " ").trim();
const industryOf = (text: string) => { const value = text.toLowerCase(); const groups: [string,string[]][] = [["消费电子",["smartphone","mobile phone","tablet","electronics","手机","平板"]],["零售与电商",["retail","ecommerce","e-commerce","shop","store"]],["通信与运营商",["telecom","network","carrier","通信"]],["制造业",["manufacturer","factory","manufacturing","生产"]],["物流与供应链",["logistics","shipping","freight","supply chain"]],["软件与科技服务",["software","cloud","technology","digital"]]]; return groups.find(([,keys]) => keys.some(key => value.includes(key)))?.[0] ?? "综合贸易"; };
const decodeXml=(value:string)=>value.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const isBusinessResult=(website:string)=>{try{return !/bing\.com|microsoft\.com|baidu\.com|zhihu\.com|wikipedia|dictionary|iciba|eudic|britannica|facebook\.com|youtube\.com|instagram\.com|linkedin\.com\/pulse/.test(new URL(website).hostname.toLowerCase())}catch{return false}};
const timedFetch=(url:string,init:RequestInit={},milliseconds=12000)=>fetch(url,{...init,signal:AbortSignal.timeout(milliseconds)});
function safeUrl(raw: string) { const value = /^https?:\/\//i.test(raw) ? raw : `https://${raw}`; const url = new URL(value); if (!["http:","https:"].includes(url.protocol) || /^(localhost|127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/i.test(url.hostname)) throw new Error("网址无效"); return url; }
async function inspectWebsite(raw:string) { const url=safeUrl(raw); let response:Response;let usedReader=false;try{response=await timedFetch(url.href,{headers:{accept:"text/html"},redirect:"follow"},10000);if(!response.ok)throw new Error()}catch{response=await timedFetch(`https://r.jina.ai/${url.href}`,{headers:{accept:"text/plain"}},15000);usedReader=true}if(!response.ok)throw new Error(`官网读取失败 (${response.status})`);const html=(await response.text()).slice(0,800000),plain=(usedReader?html:textOnly(html)).slice(0,12000);const title=(usedReader?html.match(/^Title:\s*(.+)$/mi)?.[1]:html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1])?.replace(/\s+/g," ").trim()??url.hostname;const description=html.match(/<meta[^>]+(?:name=["']description["'][^>]+content=["']([^"']+)|content=["']([^"']+)["'][^>]+name=["']description["'])/i);const summary=(description?.[1]||description?.[2]||plain.slice(0,360)).trim();const emails=[...new Set(plain.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)??[])].slice(0,5).join(", ");const phones=[...new Set(plain.match(/(?:\+?\d[\d\s().-]{7,}\d)/g)??[])].slice(0,5).join(", ");return{website:url.href,title,summary,emails,phones,industry:industryOf(`${title} ${summary} ${plain}`)}}

export async function GET(request: Request) {
  try { const db = getDb(), ownerId = owner(request); const [customers, productRows] = await Promise.all([db.select().from(customerResearch).where(eq(customerResearch.ownerId, ownerId)).orderBy(desc(customerResearch.id)), db.select().from(products).where(eq(products.ownerId, ownerId)).orderBy(desc(products.id))]); return Response.json({ customers, products: productRows }); }
  catch (error) { return Response.json({ error: error instanceof Error ? error.message : "读取失败" }, { status: 500 }); }
}

export async function POST(request: Request) {
  try {
    const body = await request.json() as Record<string, unknown>, db = getDb(), ownerId = owner(request);
    if(body.action==="discoverLeads"){const keyword=String(body.keyword??"").trim(),region=String(body.region??"").trim();if(!keyword)return Response.json({error:"请输入产品或行业关键词"},{status:400});const query=`${keyword} ${region} distributor importer supplier company`;let items:{id:string;company:string;website:string;summary:string;industry:string}[]=[];try{const brave=await timedFetch(`https://search.brave.com/search?q=${encodeURIComponent(query)}&source=web`,{headers:{"user-agent":"Mozilla/5.0",accept:"text/html"}},8000);if(brave.ok){const html=await brave.text(),blocks=[...html.matchAll(/<div class="snippet[^>]+data-pos="[^"]+"[\s\S]*?(?=<div class="snippet|<\/main>)/g)];items=blocks.map((block,index)=>{const value=block[0],website=value.match(/<a[^>]+href="(https?:\/\/[^"&]+)[^"]*"/i)?.[1]??"",title=decodeXml(value.match(/class="title search-snippet-title[^"]*"[^>]*>([\s\S]*?)<\/div>/i)?.[1]??value.match(/title="([^"]+)"/i)?.[1]??""),summary=decodeXml(value.match(/class="content [^"]*"[^>]*>([\s\S]*?)<\/div>/i)?.[1]??"");return{id:`lead-${index}`,company:title.split(/[|–—-]/)[0].trim(),website,summary,industry:industryOf(`${keyword} ${title} ${summary}`)}}).filter(x=>x.company&&isBusinessResult(x.website))}}catch{/* Continue with fallback. */}if(!items.length){const response=await timedFetch(`https://r.jina.ai/https://www.bing.com/search?q=${encodeURIComponent(query)}`,{headers:{accept:"text/plain"}},8000);if(!response.ok)throw new Error("公开网络搜索暂时不可用");const markdown=await response.text(),seen=new Set<string>();items=[...markdown.matchAll(/\[([^\]\n]{3,120})\]\((https?:\/\/[^)\s]+)\)/g)].map((match,index)=>({id:`lead-${index}`,company:decodeXml(match[1]).split(/[|–—-]/)[0].trim(),website:match[2],summary:`搜索关键词：${keyword}${region?` · 市场：${region}`:""}`,industry:industryOf(`${keyword} ${match[1]}`)})).filter(x=>{try{const host=new URL(x.website).hostname.toLowerCase();if(!isBusinessResult(x.website)||seen.has(host))return false;seen.add(host);return true}catch{return false}}).slice(0,12)}return Response.json({leads:items.slice(0,12),query})}
    if (body.action === "researchCustomer") {
      const info=await inspectWebsite(String(body.website??""));const company=String(body.company??"").trim()||info.title.split(/[|–—-]/)[0].trim();
      const [customer] = await db.insert(customerResearch).values({ ownerId, company, website:info.website, industry:info.industry, summary:info.summary, emails:info.emails, phones:info.phones, sourceTitle:info.title,updatedAt:new Date().toISOString() }).returning();
      return Response.json({ customer }, { status: 201 });
    }
    if(body.action==="refreshCustomers"){const rows=await db.select().from(customerResearch).where(eq(customerResearch.ownerId,ownerId));let updated=0;for(const row of rows){try{const info=await inspectWebsite(row.website);await db.update(customerResearch).set({industry:info.industry,summary:info.summary,emails:info.emails,phones:info.phones,sourceTitle:info.title,updatedAt:new Date().toISOString()}).where(and(eq(customerResearch.id,row.id),eq(customerResearch.ownerId,ownerId)));updated++}catch{/* Keep the stored record when a website is temporarily unavailable. */}}return Response.json({updated,total:rows.length})}
    if (body.action === "saveProduct") {
      const name = String(body.name ?? "").trim(), model = String(body.model ?? "").trim(); if (!name || !model) return Response.json({ error: "产品名称和型号不能为空" }, { status: 400 });
      const values = { ownerId, name, model, category: String(body.category ?? ""), specification: String(body.specification ?? ""), price: Math.round(Number(body.price) * 100) || 0, currency: String(body.currency ?? "USD"), status: "active" };
      const id = Number(body.id); const [product] = id ? await db.update(products).set(values).where(and(eq(products.id,id),eq(products.ownerId,ownerId))).returning() : await db.insert(products).values(values).returning(); return Response.json({ product }, { status: 201 });
    }
    if (body.action === "deleteProduct") { await db.delete(products).where(and(eq(products.id, Number(body.id)), eq(products.ownerId, ownerId))); return Response.json({ ok: true }); }
    return Response.json({ error: "不支持的操作" }, { status: 400 });
  } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "处理失败" }, { status: 500 }); }
}
